### ISSUE TITLE
Window returned to normal size from max after entering Neovim

### ISSUE THREAD

**Issue by HankelBao** [mskyaxl/wsl-terminal#112] opened 2018-07-12 08:30 UTC
After entering Neovim, the maximized window will return to normal size automatically.
The same problem doesn't exist in terms of vim8.0

I consider wsl-terminal as the best wsl terminal on Windows, but this issue is really annoying sometimes.

**Comment by mskyaxl** [comment] 2020-04-12 11:35
Hi @HankelBao, with a really really really long delay. I took over this repo not long ago. Do you still have this problem? 

I am a vim user and not so familiar with neovim(beside what I know from vim).
Do you use the GUI version of Neovim or the terminal version? I tried the terminal version and I cannot reproduce it.

**Comment by mskyaxl** [comment] 2020-04-25 10:32
closing this issue as there is no reply :)

**Closed by mskyaxl** 2020-04-25 10:32 UTC
Labels: waitForReply
