### ISSUE TITLE
Sometime can't go fullscreen on v0.8.12

### ISSUE THREAD

**Issue by feryardiant** [mskyaxl/wsl-terminal#148] opened 2019-03-24 17:02 UTC
I've been using this project as my daily basis since v0.8.10 and never had any issues whatsoever, but after upgrading to v0.8.12 I've noticed that sometimes I can't go fullscreen using <kbd>ALT + ENTER</kbd> keys and don't have idea why it could happened.

The issue is only happened after startup `wsl-terminal`, anytime I pressed <kbd>ALT + ENTER</kbd> it just echoed `^[`. But when I started using `tmux` the <kbd>ALT + ENTER</kbd> is works just fine, even I exited tmux.

![image](https://user-images.githubusercontent.com/508665/54882823-92672080-4e90-11e9-92c4-773c211ce2f3.png)

WSL-Terminal v0.8.12
Ubuntu 18.04.2
Shell ZSH 5.4.2
Windows 10 Home 64bit Version 1803 Build 17134.648
TMUX 2.6 with this [`tmux.conf`](https://github.com/feryardiant/dotfiles/blob/master/.tmux.conf)

**Comment by feryardiant** [comment] 2019-03-25 20:38
Today I realized that the issue is only happened when I am using right <kbd>ALT</kbd> key while the left <kbd>ALT</kbd> key is works just fine. Having tested it multiple times and got the same results, the right <kbd>ALT</kbd>+ <kbd>ENTER</kbd> isn't working on my machine.

Tried to roll back to v0.8.11, both left and right <kbd>ALT</kbd> + <kbd>ENTER</kbd> are working without any issues.

**Comment by mskyaxl** [comment] 2020-04-12 20:33
can you please retry on 0.9.0?

**Comment by feryardiant** [comment] 2020-04-12 21:19
HI @mskyaxl,

I can confirm that <kbd>LEFT-ALT</kbd> + <kbd>ENTER</kbd> in `v0.9.0` is works just fine. But, <kbd>RIGHT-ALT</kbd> + <kbd>ENTER</kbd> still remain the same, only have "cleaner" output. I mean, I still can't enter full screen and the `^[` is no longer appears.

I still expecting using both <kbd>LEFT-ALT</kbd> & <kbd>RIGHT-ALT</kbd> should work the same like `v0.8.11` was. All I can do is ask you, is it desired behavior?

Thanks

**Comment by mskyaxl** [comment] 2020-04-12 21:35
Thanks! I will try to reproduce it and if I can I will create an issue in mintty repo :)

**Comment by mskyaxl** [comment] 2020-04-13 11:39
Hi, @feryardiant , it looks like this issues is aleady covered by https://github.com/mintty/mintty/issues/969

I can reproduce it. I have an US international layout and I have this behavior because the ```Right-ALT``` is actually ```Alt Gr``` and does nothing.

I will close this - Please follow the mintty topic for further updates. :)

**Closed by mskyaxl** 2020-04-13 11:39 UTC
Labels: bug, mintty, waitForReply

**Comment by feryardiant** [comment] 2020-04-13 15:26
Thank you @mskyaxl 

Anyway, may I ask, which mintty version you're using on `v0.8.10`? Is it still using mintty `v2.8.4` as stated in [`v0.8.8` release](https://github.com/mskyaxl/wsl-terminal/releases/tag/v0.8.8)?
